Rocky/Models/Well.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rocky.Models
{
    public class Well
    {
        public int Id { get; set; }        
        public string WellheadRewinding { get; set; }  //отметка устья скважины
        public string WellDepth { get; set; }          //глубина скважины
        public string SoilLayerThickness { get; set; }  // толщина слоя грунта

        [Display(Name = "Soil Properties")]
        public int SoilPropertiesId { get; set; }      //id слоя грунта
        [ForeignKey("SoilPropertiesId")]                            //Чтобы установить свойство в качестве внешнего ключа, применяется атрибут [ForeignKey]:
        public virtual SoilProperties SoilProperties { get; set; }   // грунт

      

    }
}

Rocky/Controllers/PileCalculationController.cs
using Microsoft.AspNetCore.Mvc;
using Rocky.Data;
using Rocky.Models;
using System.Collections.Generic;

namespace Rocky.Controllers
{
    public class PileCalculationController : Controller
    {
        private readonly Data.ApplicationDbContext _db;

        

        public PileCalculationController(Data.ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View(); 
        }

        //Get
        public IActionResult SoilTable()
        {
            IEnumerable<SoilProperties> soilList = _db.SoilProperties;
            return View(soilList);
        }

        //Get
        public IActionResult AddSoilTable()
        {
            return View();
        }

        [HttpPost]
        [IgnoreAntiforgeryToken]
        public IActionResult AddSoilTable(SoilProperties soil)
        {
           if(ModelState.IsValid)
            {
                _db.SoilProperties.Add(soil);
                _db.SaveChanges();
                return RedirectToAction("SoilTable");
            }
            return View(soil);
        }


        //Get
        public IActionResult Edit(int? id)
        {
            if(id==null || id==0)
            {
                return NotFound();
            }

            var soil = _db.SoilProperties.Find(id);

            if(soil==null)
            {
                return NotFound();
            }

            return View(soil);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Edit(SoilProperties soil)
        {
            if(ModelState.IsValid)
            {
                _db.SoilProperties.Update(soil);
                _db.SaveChanges();
                return RedirectToAction(nameof(SoilTable));
            }

            return View(soil);
        }

        //Get
        public IActionResult Delete(int? id)
        {
            if(id==null || id==0)
            {
                return NotFound();
            }

            var soil = _db.SoilProperties.Find(id);

            if(soil==null)
            {
                return NotFound();
            }

            return View(soil);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            if(id==0 || id==null)
            {
                return NotFound();
            }

            var soil = _db.SoilProperties.Find(id);

            _db.SoilProperties.Remove(soil);
            _db.SaveChanges();

            return RedirectToAction(nameof(SoilTable));
        }




    }
}

Rocky/Controllers/WellController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Rocky.Controllers
{
    public class WellController : Controller
    {
        public readonly Data.ApplicationDbContext _db;

        public WellController(Data.ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Rocky/Views/Well/Index.cshtml
@model IEnumerable<Well>

<div class="row">
    <div class="col-12">
        <h4 class="text-center">Таблица грунтового основания</h4><br />
        <table border="1" width="100%" cellpadding="8">
            <tr>
                <th class="text-center">Номер грунта</th>
                <th class="text-center">Наименование грунта</th>
                <th class="text-center">Крупность</th>
                <th class="text-center">Прочность</th>
                <th class="text-center">Пористость, e</th>
                <th class="text-center">Показатель текучести, IL</th>
                <th class="text-center">Угол внутреннего трения, &phi;</th>
                <th class="text-center">Удельное сцепление, c (т/м2)</th>
                <th class="text-center">Модуль деформации, Е (МПа)</th>
                <th class="text-center">Удалить или редактировать грунт</th>
            </tr>


            @foreach (var item in Model)
            {
                <tr>
                    <th class="text-center">
                        @item.NumberOfSoil
                    </th>
                    <th class="text-center">
                        @item.Name
                    </th>

                    <th class="text-center">
                        @item.NameOfSand
                    </th>
                    <th class="text-center">
                        @item.SoilStrengthForSand
                    </th>
                    <th class="text-center">
                        @item.PorosityCoefficient
                    </th>
                    <th class="text-center">
                        @item.YieldRate
                    </th>
                    <th class="text-center">
                        @item.AngleOfInternalFriction
                    </th>
                    <th class="text-center">
                        @item.SpecificAdhesion
                    </th>
                    <th class="text-center">
                        @item.DeformationModulus
                    </th>
                    <th class="text-center">
                        <div class="w-75 btn-group text-center" role="group">
                            <a asp-controller="PileCalculation" asp-action="Edit" asp-route-Id="@item.Id" class="btn btn-primary mx-2"><i class="fas fa-edit text-center"></i> &nbsp;</a>

                            <a asp-controller="PileCalculation" asp-action="Delete" asp-route-Id="@item.Id" class="btn btn-danger mx-2"><i class="fas fa-trash-alt text-center"></i> &nbsp; </a>
                        </div>
                    </th>
                </tr>
            }
        </table>
    </div>
</div>
<br />
<br />
<div>
    <a asp-controller="PileCalculation" asp-action="AddSoilTable" class="btn btn-primary">
        <i class="fas fa-plus"></i> &nbsp; Добавить грунт
    </a>
    <a asp-controller="PileCalculation" asp-action="Index" class="btn btn-success w-35">
        <i class="fas fa-sign-out-alt"></i> &nbsp; Назад
    </a>
</div>